/* New Pratap Tools Commerce API — production-ready integration gateway.
   Secrets never leave this server. Configure providers from Admin → Integrations.
*/
const http=require('http'),fs=require('fs'),path=require('path'),url=require('url'),crypto=require('crypto');
const {testProvider,createPayment,sendNotification}=require('./integrations/provider-adapters');
const ROOT=__dirname, ENV=path.join(ROOT,'.env.local'), DATA=path.join(ROOT,'.data'), DB=path.join(DATA,'commerce.json'), SECRET=path.join(DATA,'integration-secrets.enc');
const PORT=process.env.PORT||8787;
const INTEGRATION_PANEL_PASSWORD=process.env.INTEGRATION_PANEL_PASSWORD||'270303';
const schema={
 supabase:['SUPABASE_URL','SUPABASE_PUBLISHABLE_KEY','SUPABASE_SERVICE_ROLE_KEY'],auth:['AUTH_PROVIDER','AUTH_API_KEY'],realtime:['REALTIME_URL','REALTIME_API_KEY'],storage:['STORAGE_URL','STORAGE_API_KEY'],
 payment:['PAYMENT_PROVIDER','RAZORPAY_KEY_ID','RAZORPAY_KEY_SECRET','RAZORPAY_WEBHOOK_SECRET','CASHFREE_APP_ID','CASHFREE_SECRET_KEY','PHONEPE_CLIENT_ID','PHONEPE_CLIENT_SECRET','PAYU_MERCHANT_KEY','PAYU_SALT'],webhooks:['PAYMENT_WEBHOOK_SECRET'],
 courier:['COURIER_PROVIDER','COURIER_API_KEY','COURIER_API_SECRET','SHIPROCKET_EMAIL','SHIPROCKET_PASSWORD','DELHIVERY_API_TOKEN','DTDC_API_KEY','BLUEDART_API_KEY','XPRESSBEES_API_KEY'],tracking:['COURIER_TRACKING_API_KEY','DELHIVERY_API_TOKEN'],
 whatsapp:['WHATSAPP_ACCESS_TOKEN','WHATSAPP_PHONE_NUMBER_ID'],catalog:['WHATSAPP_CATALOG_ID'],email:['EMAIL_PROVIDER','RESEND_API_KEY','SENDGRID_API_KEY','SMTP_HOST','SMTP_USER','SMTP_PASSWORD','EMAIL_FROM'],sms:['SMS_PROVIDER','MSG91_AUTH_KEY','TWILIO_ACCOUNT_SID','TWILIO_AUTH_TOKEN','TWILIO_FROM'],push:['FIREBASE_PROJECT_ID','FIREBASE_CLIENT_EMAIL','FIREBASE_PRIVATE_KEY'],
 maps:['GOOGLE_MAPS_API_KEY'],accounting:['ACCOUNTING_PROVIDER','ACCOUNTING_API_KEY'],invoice:['INVOICE_PROVIDER','INVOICE_API_KEY'],analytics:['GOOGLE_ANALYTICS_ID'],merchant:['GOOGLE_MERCHANT_ID'],meta:['META_PIXEL_ID','META_ACCESS_TOKEN'],googleads:['GOOGLE_ADS_ID','GOOGLE_ADS_CONVERSION_ID'],monitoring:['SENTRY_DSN'],security:['SENTRY_DSN'],crm:['CRM_PROVIDER','CRM_API_KEY'],support:['SUPPORT_PROVIDER','SUPPORT_API_KEY'],warehouse:['WAREHOUSE_API_URL','WAREHOUSE_API_KEY'],supplier:['SUPPLIER_API_URL','SUPPLIER_API_KEY'],search:['SEARCH_PROVIDER','SEARCH_API_KEY'],reviews:['REVIEWS_PROVIDER','REVIEWS_API_KEY'],abandoned:['MESSAGING_RECOVERY_API_KEY'],'live-support':['LIVE_SUPPORT_API_URL','LIVE_SUPPORT_API_KEY'],backup:[]
};
function ensure(){fs.mkdirSync(DATA,{recursive:true});if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify({products:[],orders:[],customers:[],notifications:[],banners:[],updatedAt:new Date().toISOString()},null,2));}
function readEnv(){const out={};if(!fs.existsSync(ENV))return out;for(const line of fs.readFileSync(ENV,'utf8').split(/\r?\n/)){const m=line.match(/^([A-Z0-9_]+)=(.*)$/);if(m)out[m[1]]=m[2].replace(/\\n/g,'\n')}return out}
function master(){return process.env.NPT_MASTER_KEY||'development-only-change-me';}
function enc(obj){const iv=crypto.randomBytes(12),key=crypto.createHash('sha256').update(master()).digest();const c=crypto.createCipheriv('aes-256-gcm',key,iv);const data=Buffer.concat([c.update(JSON.stringify(obj),'utf8'),c.final()]);return JSON.stringify({iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),data:data.toString('base64')});}
function dec(raw){try{const x=JSON.parse(raw),key=crypto.createHash('sha256').update(master()).digest(),d=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(x.iv,'base64'));d.setAuthTag(Buffer.from(x.tag,'base64'));return JSON.parse(Buffer.concat([d.update(Buffer.from(x.data,'base64')),d.final()]).toString('utf8'));}catch{return null}}
function loadSecrets(){ensure();if(fs.existsSync(SECRET)){const s=dec(fs.readFileSync(SECRET,'utf8'));if(s)return s}return readEnv()}
function saveSecrets(v){ensure();fs.writeFileSync(SECRET,enc(v),{mode:0o600});}
function db(){ensure();return JSON.parse(fs.readFileSync(DB,'utf8'));}
function saveDb(d){d.updatedAt=new Date().toISOString();fs.writeFileSync(DB,JSON.stringify(d,null,2));}
function json(res,status,data){res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':process.env.ALLOWED_ORIGIN||'*','access-control-allow-methods':'GET,POST,PUT,OPTIONS','access-control-allow-headers':'content-type,authorization'});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>2e6)req.destroy()});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}})})}
function status(){const e=loadSecrets(),configured={};for(const [id,keys] of Object.entries(schema))configured[id]=keys.length===0||keys.some(k=>e[k]);return {ok:true,environment:process.env.NODE_ENV||'development',configured,serverTime:new Date().toISOString(),credentialStore:fs.existsSync(SECRET)?'encrypted-file':'environment'};}
function adminToken(){return process.env.ADMIN_API_TOKEN||'npt-dev-admin-token-change-me';}
function adminAuth(req){const h=req.headers.authorization||'';return h.startsWith('Bearer ') && h.slice(7)===adminToken();}
function integrationAuth(req){const h=req.headers['x-integration-token']||'';return h===crypto.createHash('sha256').update(`${INTEGRATION_PANEL_PASSWORD}:${adminToken()}`).digest('hex');}
ensure();
const server=http.createServer(async(req,res)=>{const p=url.parse(req.url,true).pathname;
 if(req.method==='OPTIONS')return json(res,204,{});
 try{
  if(req.method==='GET' && !p.startsWith('/api/')){
    // Keep the admin app on a trailing-slash URL so relative navigation remains stable.
    if(p==='/admin-panel') { res.writeHead(301,{location:'/admin-panel/'}); return res.end(); }
    let requested=p==='/'?'/customer-store/index.html':p;
    if(p.startsWith('/assets/')) requested='/customer-store'+p;
    // Resolve assets relative to the customer store when it is mounted at /.
    if(p==='/' || p==='/index.html') requested='/customer-store/index.html';
    else if(p==='/styles.css') requested='/customer-store/styles.css';
    else if(p==='/app.js') requested='/customer-store/app.js';
    else if(p==='/admin-panel' || p==='/admin-panel/') requested='/admin-panel/index.html';
    const safe=path.normalize(requested).replace(/^\.\.(?:[\\/]|$)/g,'');
    const file=path.join(ROOT,'.'+safe);
    if(file.startsWith(ROOT) && fs.existsSync(file) && fs.statSync(file).isFile()){
      const ext=path.extname(file).toLowerCase(),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp'};
      res.writeHead(200,{'content-type':types[ext]||'application/octet-stream','cache-control':ext==='.html'?'no-cache':'public,max-age=3600'});return res.end(fs.readFileSync(file));
    }
  }
  if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true,service:'New Pratap Tools Commerce API',version:'25.0.0',time:new Date().toISOString()});
  if(req.method==='POST'&&p==='/api/admin/login'){const b=await body(req),email=process.env.ADMIN_EMAIL||'admin@newprataptools.in',pass=process.env.ADMIN_PASSWORD||(process.env.NODE_ENV==='production'?'change-me':'admin123');if(b.email!==email||b.password!==pass)return json(res,401,{ok:false,error:'Invalid admin credentials'});return json(res,200,{ok:true,token:adminToken()});}
  if(req.method==='POST'&&p==='/api/integrations/unlock'){if(!adminAuth(req))return json(res,401,{ok:false,error:'Admin authentication required'});const b=await body(req);if(String(b.password||'')!==String(INTEGRATION_PANEL_PASSWORD))return json(res,403,{ok:false,error:'Invalid integration panel password'});const token=crypto.createHash('sha256').update(`${INTEGRATION_PANEL_PASSWORD}:${adminToken()}`).digest('hex');return json(res,200,{ok:true,token});}
  if(req.method==='GET'&&p==='/api/integrations/status')return json(res,200,status());
  if(req.method==='GET'&&p==='/api/integrations/config')return json(res,200,{ok:true,schema,configured:status().configured});
  if(req.method==='POST'&&p==='/api/integrations/config'){
    if(!adminAuth(req)||!integrationAuth(req))return json(res,401,{ok:false,error:'Admin authentication required'});const b=await body(req),id=b.id,values=b.values||{};if(!schema[id])return json(res,400,{ok:false,error:'Unknown integration'});const current=loadSecrets();for(const k of schema[id])if(Object.prototype.hasOwnProperty.call(values,k)&&values[k]!==undefined&&String(values[k]).trim())current[k]=String(values[k]);saveSecrets(current);return json(res,200,{ok:true,id,configured:status().configured[id],message:'Credentials encrypted server-side'});
  }
  if(req.method==='POST'&&p==='/api/integrations/test'){
    if(!adminAuth(req)||!integrationAuth(req))return json(res,401,{ok:false,error:'Admin authentication required'});const b=await body(req),e=loadSecrets(),result=await testProvider(b.id,e);return json(res,200,{ok:true,id:b.id,result});
  }
  if(req.method==='POST'&&p==='/api/payments/create') {const b=await body(req),e=loadSecrets();if(!status().configured.payment)return json(res,400,{ok:false,error:'Payment provider is not configured'});const result=await createPayment(b.order,e);return json(res,200,{ok:true,result});}
  if(req.method==='POST'&&p==='/api/payments/verify'){const b=await body(req),e=loadSecrets();if((e.PAYMENT_PROVIDER||'').toLowerCase().includes('razor')){if(!e.RAZORPAY_KEY_SECRET) return json(res,400,{ok:false,error:'Razorpay secret not configured'});const payload=`${b.razorpay_order_id}|${b.razorpay_payment_id}`;const expected=crypto.createHmac('sha256',e.RAZORPAY_KEY_SECRET).update(payload).digest('hex');return json(res,200,{ok:crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(String(b.razorpay_signature||''))),paymentId:b.razorpay_payment_id,orderId:b.razorpay_order_id});}return json(res,400,{ok:false,error:'Payment verification adapter not configured for this provider'});}
  if(req.method==='POST'&&p==='/api/payments/webhook'){const raw=await body(req),e=loadSecrets();const sig=req.headers['x-razorpay-signature'];let verified=true;if((e.PAYMENT_PROVIDER||'').toLowerCase().includes('razor')){const payload=JSON.stringify(raw);const expected=crypto.createHmac('sha256',e.RAZORPAY_WEBHOOK_SECRET||'').update(payload).digest('hex');verified=!!sig&&crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(String(sig)));}return json(res,verified?200:401,{ok:verified,received:true});}
  if(req.method==='POST'&&p==='/api/notifications/send') {const b=await body(req),e=loadSecrets();const result=await sendNotification(b.channel,b.message||{},e);return json(res,200,{ok:true,result});}
  if(req.method==='GET'&&p==='/api/store/state'){const d=db();if(adminAuth(req))return json(res,200,{ok:true,...d});return json(res,200,{ok:true,products:d.products,banners:d.banners,updatedAt:d.updatedAt});}
  if(req.method==='GET'&&p==='/api/store/customer'){const q=url.parse(req.url,true).query||{},mobile=String(q.mobile||'').replace(/\D/g,''),email=String(q.email||'').toLowerCase();if(!mobile&&!email)return json(res,400,{ok:false,error:'Mobile or email required'});const d=db();const customer=d.customers.find(c=>(mobile&&String(c.mobile||'').replace(/\D/g,'')===mobile)||(email&&String(c.email||'').toLowerCase()===email));if(!customer)return json(res,404,{ok:false,error:'Customer not found'});return json(res,200,{ok:true,customer});}
  if(req.method==='PUT'&&p==='/api/store/customer'){const b=await body(req),c=b.customer||{};if(!c.mobile&&!c.email)return json(res,400,{ok:false,error:'Customer mobile or email required'});const d=db(),mobile=String(c.mobile||'').replace(/\D/g,''),email=String(c.email||'').toLowerCase(),i=d.customers.findIndex(x=>(mobile&&String(x.mobile||'').replace(/\D/g,'')===mobile)||(email&&String(x.email||'').toLowerCase()===email));if(i<0)return json(res,404,{ok:false,error:'Customer not found'});d.customers[i]={...d.customers[i],...c};saveDb(d);return json(res,200,{ok:true,customer:d.customers[i]});}
  if(req.method==='PUT'&&p==='/api/store/state'){if(!adminAuth(req))return json(res,401,{ok:false,error:'Admin authentication required'});const b=await body(req),d=db();if(Array.isArray(b.products))d.products=b.products;if(Array.isArray(b.banners))d.banners=b.banners;d.updatedAt=new Date().toISOString();saveDb(d);return json(res,200,{ok:true,products:d.products,banners:d.banners,updatedAt:d.updatedAt});}
  if(req.method==='POST'&&p==='/api/store/customer'){const b=await body(req),c=b.customer||{};if(!c.mobile)return json(res,400,{ok:false,error:'Customer mobile required'});const d=db(),mobile=String(c.mobile).replace(/\D/g,''),email=String(c.email||'').toLowerCase(),i=d.customers.findIndex(x=>String(x.mobile||'').replace(/\D/g,'')===mobile||(email&&String(x.email||'').toLowerCase()===email));if(i>=0)d.customers[i]={...d.customers[i],...c};else d.customers.push(c);saveDb(d);return json(res,200,{ok:true,customer:i>=0?d.customers[i]:c});}
  if(req.method==='POST'&&p==='/api/store/order'){const b=await body(req),d=db();if(!b.order?.id)return json(res,400,{ok:false,error:'Order required'});const order=b.order;const idx=d.orders.findIndex(o=>o.id===order.id);const isNew=idx<0;if(idx>=0)d.orders[idx]=order;else d.orders.unshift(order);if(isNew&&Array.isArray(order.items)){for(const item of order.items){const pi=d.products.findIndex(p=>p.id===item.id);if(pi>=0)d.products[pi].stock=Math.max(0,Number(d.products[pi].stock||0)-Number(item.qty||0));}}if(b.customer){const mobile=String(b.customer.mobile||'').replace(/\D/g,'');const email=String(b.customer.email||'').toLowerCase();const ci=d.customers.findIndex(c=>String(c.mobile||'').replace(/\D/g,'')===mobile||(email&&String(c.email||'').toLowerCase()===email));if(ci>=0)d.customers[ci]={...d.customers[ci],...b.customer};else d.customers.push(b.customer);}
    const adminKey='order:'+order.id;const customerKey='customer-order:'+order.id;d.notifications=d.notifications||[];if(!d.notifications.some(n=>n.key===adminKey))d.notifications.unshift({id:'n-admin-'+order.id,key:adminKey,type:'order',audience:'admin',title:'New order '+order.id,text:`${order.customer?.name||'Customer'} placed an order using ${order.payment||'UPI'}.`,read:false,date:new Date().toISOString(),orderId:order.id});if(!d.notifications.some(n=>n.key===customerKey))d.notifications.unshift({id:'n-customer-'+order.id,key:customerKey,type:'order',audience:'customer',customerRef:order.customer?.mobile||order.customer?.email||order.customerId,orderId:order.id,title:'Order placed · '+order.id,text:'Your order has been placed. We will notify you as it moves through processing and dispatch.',read:false,date:new Date().toISOString()});d.updatedAt=new Date().toISOString();saveDb(d);return json(res,200,{ok:true,order,updatedAt:d.updatedAt});}
  if(req.method==='PUT'&&p.startsWith('/api/store/order/')){if(!adminAuth(req))return json(res,401,{ok:false,error:'Admin authentication required'});const id=decodeURIComponent(p.split('/').pop()),b=await body(req),d=db(),i=d.orders.findIndex(o=>o.id===id);if(i<0)return json(res,404,{ok:false,error:'Order not found'});d.orders[i]={...d.orders[i],...b.order};const order=d.orders[i];d.notifications=d.notifications||[];d.notifications.unshift({id:'n-update-'+order.id+'-'+Date.now(),type:'order',audience:'customer',customerRef:order.customer?.mobile||order.customer?.email||order.customerId,orderId:order.id,title:'Order update · '+order.id,text:`Your order status is now ${order.status}.`,read:false,date:new Date().toISOString()});d.updatedAt=new Date().toISOString();saveDb(d);return json(res,200,{ok:true,order,notifications:d.notifications,updatedAt:d.updatedAt});}
  if(req.method==='GET'&&p==='/api/store/orders'){const d=db();if(adminAuth(req))return json(res,200,{ok:true,orders:d.orders,customers:d.customers,notifications:d.notifications,updatedAt:d.updatedAt||null});const q=url.parse(req.url,true).query||{},mobile=String(q.mobile||'').replace(/\D/g,''),email=String(q.email||'').toLowerCase();if(!mobile&&!email)return json(res,400,{ok:false,error:'Customer mobile or email required'});const orders=d.orders.filter(o=>{const om=String(o.customer?.mobile||'').replace(/\D/g,'');const oe=String(o.customer?.email||'').toLowerCase();return (mobile&&om===mobile)||(email&&oe===email)});const notifications=(d.notifications||[]).filter(n=>n.audience==='customer'&&((mobile&&String(n.customerRef||'').replace(/\D/g,'')===mobile)||(email&&String(n.customerRef||'').toLowerCase()===email)));return json(res,200,{ok:true,orders,notifications,updatedAt:d.updatedAt||null});}
  json(res,404,{ok:false,error:'Not found'});
 }catch(e){json(res,e.status||500,{ok:false,error:e.message,details:e.data||undefined});}
});
server.listen(PORT,'0.0.0.0',()=>console.log(`New Pratap Tools API running on port ${PORT}`));
